services:
  servidor-bd:
    image: crate
    ports:
      - 4200:4200
    command: ["crate",
              "-Cdiscovery.type=single-node"]
  cliente-crate:
    build: .
    ports:
      - 4201:4201
    links:
      - servidor-bd
  web:
    image: httpd
    volumes:
      - ./public:/usr/local/apache2/htdocs
    ports:
      - 8080:80
    links:
      - cliente-crate
