apiVersion: v1
kind: PersistentVolume

metadata:
  name: data-crate-vps

spec:
  storageClassName: crate-vol
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/home/joel/as/Proyecto/main/db/"