apiVersion: v1
kind: PersistentVolume

metadata:
  name: data-volume-vps

spec:
  storageClassName: vol
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/home/joel/as/Proyecto/kubernetes/main/public/"