apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: data-volume-vp

spec:
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  hostPath:
    path: "../main/public/"