apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-crate
spec:
  replicas: 1
  selector:
    matchLabels:
      component: crate
  template:
    metadata:
      labels:
        component: crate
    spec:
      volumes:
        - name: almacenamiento-bd
          persistentVolumeClaim:
            claimName: data-crate-vp
      initContainers:
        - name: init-sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      containers:
        - name: mi-crate-pod
          image: crate
          command:
            - /docker-entrypoint.sh
            - -Cnode.name="node"
            - -Ccluster.name="cluster"
            - -Ccluster.initial_master_nodes=crate-0
          ports:
            - containerPort: 4200
          volumeMounts:
            - name: almacenamiento-bd
              mountPath: /db-data